# This file contains values from Cookiecutter

default_context:
  project_name: "Average Price Calculator"
  project_slug: "average_price_calculator"
  project_description: "A tool for calculating weighted average prices after additional purchases"
  username: "Aram Aleksanyan"
  email: "Aram.Aleksanyan@waveaccess.global"
  vcs_remote_type: "github"
  minimal_python_version: "3.12"
  version: "0.1.0"
  line_length: "100"
  package_manager: "poetry"

  python_linter: "ruff"
  python_formatter: "black"
  python_type_checker: "mypy"

  include_cli_example: "n"
  include_docker_sample: "n"
  include_notebooks_sample: "y"
